---
- name: set up local dir with packer json and build files
  hosts: localhost
  gather_facts: no
  vars:
    opt_packer_setup_username: vagrant
    opt_packer_setup_password: vagrant
    opt_packer_setup_headless: true
    opt_packer_setup_builder: qemu

  pre_tasks:
  - name: check that the Ansible version is at least 2.9
    assert:
      that:
      - ansible_version.major >= 2
      - ansible_version.minor >= 9
      msg: packer-windoze requires Ansible 2.9 or newer to run, please upgrade or checkout devel before running

  - name: check that the provider is valid
    assert:
      that:
      - opt_packer_setup_builder in ['hyperv', 'qemu', 'virtualbox']
      msg: packer-windoze only supports the hyperv, qemu, and virtualbox provider

  - name: check that pypsrp is installed
    command: python -c "import pypsrp"
    changed_when: False

  roles:
  - packer-setup
