---
- name: set show hidden files/folders and file extensions for the default user profile
  win_regedit:
    path: HKLM:\ANSIBLE\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: '{{ item.name }}'
    data: '{{ item.data }}'
    type: dword
    state: present
    hive: C:\Users\Default\NTUSER.dat
  loop:
  - name: Hidden
    data: 1
  - name: HideFileExt
    data: 0

- name: set This PC as the default view for Windows Explorer for the default user profile
  win_regedit:
    path: HKLM:\ANSIBLE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: LaunchTo
    data: 1
    type: dword
    state: present
    hive: C:\Users\Default\NTUSER.dat
  when:  # this is only valid for 2016/10+
  - man_host_type != '2012'
  - man_host_type != '2012r2'

- name: set show hidden files/folders and file extensions for the current user profile
  win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: '{{ item.name }}'
    data: '{{ item.data }}'
    type: dword
    state: present
  loop:
  - name: Hidden
    data: 1
  - name: HideFileExt
    data: 0

- name: set This PC as the default view for Windows Explorer for the current user profile
  win_regedit:
    path: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: LaunchTo
    data: 1
    type: dword
    state: present
  when:
  - man_host_type != '2012'
  - man_host_type != '2012r2'

- name: disable automatic updates (prevents TrustedInstaller startup thrash on older images)
  win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
    name: NoAutoUpdate
    data: 1
    type: dword
    state: present

- name: install set Chocolatey packages
  win_chocolatey:
    name: '{{ man_personalize_choco_packages }}'  # FIXME: Filter out pwsh for Server 2012
    ignore_checksums: yes
    state: present
  when:
  - man_personalize_choco_packages|count > 0
  - man_personalize_choco_packages[0] != ''
  become: yes
  vars:  # run with become as we aren't sure what packages the user has specified
    ansible_become_user: '{{ ansible_user }}'
    ansible_become_pass: '{{ ansible_password }}'

- name: get pwsh path
  win_shell: |
    $pwsh = Get-Command -Name pwsh.exe -CommandType Application -ErrorAction SilentlyContinue
    if ($pwsh) {
        (New-Object -ComObject Scripting.FileSystemObject).GetFile($pwsh.Source).ShortPath
    }
  register: pri_personalize_pwsh_path

- name: set up powershell subsystem from PSRemoting
  win_lineinfile:
    path: C:\ProgramData\ssh\sshd_config
    line: Subsystem       powershell {{ pri_personalize_pwsh_path.stdout | trim }} -sshs -NoLogo -NoProfile
    state: present
  when: pri_personalize_pwsh_path.stdout| trim | bool

- name: install the VirtualBox Guest Additions
  include_tasks: virtualbox.yml
  when: man_provider == 'virtualbox'

- name: install the QEMU Guest Additions
  include_tasks: qemu.yml
  when: man_provider == 'qemu'
