---
- name: set registry flag that shows updates for compatible anti-viruses
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\QualityCompat
    name: cadca5fe-87d3-4b96-b7fb-a231484277cc
    data: 0
    type: dword

- name: enable verbose logging (WUA seems to fail on some installs without this)
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Trace
    name: '{{ item.name }}'
    data: '{{ item.data }}'
    type: dword
  loop:
  - name: Flags
    data: 7
  - name: Level
    data: 4

- name: install updates and reboot along the way
  win_updates:
    category_names: '*'
    state: installed
    reboot: yes

- name: remove verbose Windows Update logging
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Trace
    state: absent
    delete_key: yes

- name: stop the Windows Update service
  win_service:
    name: wuauserv
    state: stopped

- name: clear update log after it blew up from the above
  win_file:
    path: C:\Windows\WindowsUpdate.log
    state: absent
  ignore_errors: yes

- name: start the Windows Update service
  win_service:
    name: wuauserv
    state: started
