# Server 2012 doesn't have cleanmgr setup by default, this
# needs to be copied from the relevant winsxs folder to it's intended location
# before running.
---
- name: copy cleanmgr from winsxs
  win_copy:
    src: C:\Windows\WinSxS\amd64_microsoft-windows-cleanmgr_31bf3856ad364e35_6.2.9200.16384_none_c60dddc5e750072a\cleanmgr.exe
    dest: C:\Windows\System32\cleanmgr.exe
    remote_src: True

- name: copy cleanmgr mui from winsxs
  win_copy:
    src: C:\Windows\WinSxS\amd64_microsoft-windows-cleanmgr.resources_31bf3856ad364e35_6.2.9200.16384_en-us_b6a01752226afbb3\cleanmgr.exe.mui
    dest: C:\Windows\System32\en-US\cleanmgr.exe.mui
    remote_src: True

- name: run cleanmgr with everything set
  block:
  - name: set custom flags for cleanmgr run
    win_shell: |
      $volume_caches = Get-ChildItem -Path "HKLM:\Software\Microsoft\Windows\CurrentVersion\Explorer\VolumeCaches"
      foreach ($volume_cache in $volume_caches) {
          New-ItemProperty -Path $volume_cache.PSPath -Name StateFlags0666 -Value 2 -Type DWORD -Force | Out-Null
      }

  - name: run cleanmgr with custom flag
    win_command: cleanmgr.exe /sagerun:666

  always:
  - name: clear custom flags after cleanmgr run
    win_shell: |
      $volume_caches = Get-ChildItem -Path "HKLM:\Software\Microsoft\Windows\CurrentVersion\Explorer\VolumeCaches"
      foreach ($volume_cache in $volume_caches) {
          Remove-ItemProperty -Path $volume_cache.PSPath -Name StateFlags0666 -Force | Out-Null
      }
