- name: check if VM is already running
  community.general.pids:
    pattern: '{{ ("qemu-system-x86_64 -name windoze-" ~ inventory_hostname ~ " -machine") | regex_escape("posix_basic") }}*'
  register: qemu_pid

- name: kill existing VM if force is specified
  command: kill {{ item }}
  loop: '{{ qemu_pid.pids }}'
  when: force

- name: start VM if not already running
  when: force or qemu_pid.pids | length == 0
  block:
  - name: enesure older artifacts are removed
    file:
      path: '{{ playbook_dir }}/output/{{ inventory_hostname }}/{{ item }}'
      state: absent
    loop:
    - qemu
    - box
    - vagrant.box

  - name: create QEMU build dir
    file:
      path: '{{ playbook_dir }}/output/{{ inventory_hostname }}/qemu'
      state: directory

  - name: create QEMU hdd image
    command: >-
      qemu-img create
      -f qcow2
      -o preallocation=off
      {{ (playbook_dir ~ '/output/' ~ inventory_hostname ~ '/qemu/' ~ inventory_hostname ~ '-vm.qcow2') | quote }}
      40960M

  - name: set runner args for qemu
    set_fact:
      invoke_runner_args: >-
        qemu-system-x86_64
        -name windoze-{{ inventory_hostname }}
        -machine type=pc,accel=kvm
        -smp cpus=2,sockets=2
        -m 2048M
        -vnc 127.0.0.1:{{ (guest_port | int) + 1 }}
        -netdev user,id=user0,hostfwd=tcp::{{ guest_port }}-:5985
        -device virtio-net,netdev=user0
        -drive file={{ iso_src | quote }},index=0,media=cdrom
        -drive file={{ secondary_iso_src | quote }},index=1,media=cdrom
        -drive file={{ (playbook_dir ~ '/output/common/virtio-win.iso') | quote }},index=2,media=cdrom
        -drive file={{ (playbook_dir ~ '/output/' ~ inventory_hostname ~ '/qemu/' ~ inventory_hostname ~ '-vm.qcow2') | quote }},if=virtio,cache=writeback,discard=ignore,format=qcow2
        -boot once=d
        -daemonize

  - name: add non-headless display
    set_fact:
      invoke_runner_args: '{{ invoke_runner_args }} -display gtk'
    when: not headless

  - name: start up QEMU VM
    command: '{{ invoke_runner_args }}'
