- name: check if PID file exists
  stat:
    path: '{{ playbook_dir }}/output/{{ inventory_hostname }}/vm.pid'
  register: pid_stat

- name: wait for VM process to finish
  when: pid_stat.stat.exists
  block:
  - name: get VM PID
    slurp:
      path: '{{ playbook_dir }}/output/{{ inventory_hostname }}/vm.pid'
    register: vm_pid

  - name: wait for VM process to complete
    wait_for:
      path: /proc/{{ vm_pid.content | b64decode }}/status
      state: absent

  - name: remove vm PID file
    file:
      path: '{{ playbook_dir }}/output/{{ inventory_hostname }}/vm.pid'
      state: absent

- set_fact:
    box_path: '{{ playbook_dir }}/output/{{ inventory_hostname }}/box'

- name: create box folder
  file:
    path: '{{ box_path }}'
    state: directory

- name: template Vagrantfile
  template:
    src: Vagrantfile.tmpl
    dest: '{{ box_path }}/Vagrantfile'
  register: box_template

- name: compress VM image
  command: >-
    qemu-img convert
    -c
    -O qcow2
    {{ (playbook_dir ~ '/output/' ~ inventory_hostname ~ '/qemu.qcow2') | quote }}
    {{ (box_path ~ '/box.img') | quote }}
  register: box_img
  args:
    creates: '{{ box_path }}/box.img'

- name: remove original VM img
  file:
    path: '{{ playbook_dir }}/output/{{ inventory_hostname }}/qemu.qcow2'
    state: absent
  when: box_img is changed

- name: get image details
  command: qemu-img info --output=json {{ (box_path ~ '/box.img') | quote }}
  register: qemu_img_info
  changed_when: False

- name: build box metadata
  set_fact:
    box_metadata:
      format: qcow2
      provider: libvirt
      virtual_size: '{{ (((qemu_img_info.stdout | trim | from_json)["virtual-size"] | int) / 1073741824) | int }}'

- name: create metadata.json
  copy:
    content: '{{ box_metadata | to_json }}'
    dest: '{{ box_path }}/metadata.json'
  register: box_metadata

- name: create box
  shell: >-
    tar
    --create
    --verbose
    --sparse
    ./metadata.json
    ./Vagrantfile
    ./box.img
    | pigz -c > ../vagrant.box
  args:
    chdir: '{{ box_path }}'
  when: >-
    box_template is changed or
    box_img is changed or
    box_metadata is changed
