---
# Features on Demand won't reinstall on Server 2016+ so let's not do it for now
- name: uninstall all unused Windows Features if function is available
  win_shell: Get-WindowsFeature | Where-Object { $_.InstallState -eq 'Available' } | Uninstall-WindowsFeature -Remove
  when: inventory_hostname == 'win-2012r2'
